version: '3'
services:
        web:
                image: flow_v1
                build: .
                ports:
                        - "8087:8087"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
